### ISSUE TITLE
Simple_Unet is missing MaxPool layers

### ISSUE THREAD

**Issue by sabeenlohawala** [sabeenlohawala/tissue_labeling#42]
https://github.com/sabeenlohawala/tissue_labeling/blob/18de49f5b831edc428b3c42fc32dab8504376b69/TissueLabeling/models/simple_unet.py#L19

The downsampling blocks have an extra convolutional layer here. Remove this and restructure the code to have MaxPool after the encoder blocks, like in the paper.

**Comment by hvgazula** [comment]
not resolved in simple_unet.py but resolved in nobrainer_unet.py (which is the same as https://github.com/MGH-LEMoN/ddpm-labels/blob/main/ddpm_labels/models/model3.py)
