### ISSUE TITLE
Simple_Unet doesn't run as standalone file

### ISSUE THREAD

**Issue by sabeenlohawala** [sabeenlohawala/tissue_labeling#43]
https://github.com/sabeenlohawala/tissue_labeling/blob/18de49f5b831edc428b3c42fc32dab8504376b69/TissueLabeling/models/simple_unet.py#L97C5-L102C6

`TypeError: forward() takes 2 positional arguments but 3 were given`

**Comment by sabeenlohawala** [comment]
steps:
1) make original simple_unet work
2) remove the positional embeddings
3) add nr_of_classes

**Comment by hvgazula** [comment]
resolved...simply remove the input size corresponding to the time embedding which has been deleted in this version.
