### ISSUE TITLE
When are Input layers necessary?

### ISSUE THREAD

**Issue by sabeenlohawala** [sabeenlohawala/tissue_labeling#45]
https://github.com/sabeenlohawala/tissue_labeling/blob/95b55f6fb072387539a946945da95d054b93ddde/TissueLabeling/models/original_unet_tf.py#L37

Question also applies to pytorch unet models:
https://github.com/sabeenlohawala/tissue_labeling/blob/dev/TissueLabeling/models/original_unet.py
https://github.com/sabeenlohawala/tissue_labeling/blob/dev/TissueLabeling/models/attention_unet.py

**Comment by hvgazula** [comment]
In keras/tf, notice that most layers have an input argument called `input_shape`. so, when you specify that there is no need for `InputLayer`. In other words, if you don't specify `input_shape`, you use `InputLayer`. aka, `input_shape` and `InputLayer` are technically "mutually-exclusive". Pytorch has no such thing and this is pretty straightforward. I hope this makes sense.

**Comment by hvgazula** [comment]
answer to your ques in https://github.com/sabeenlohawala/tissue_labeling/blob/fa9b1723b372f5b566db592a9a04d08dc0107721/TissueLabeling/models/original_unet_tf.py#L55

remember kernels/filters is the same as channels..so in the last layer (just before output), you apply the same number of kernels as the number of channels expected in the output.
